# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1338fe2f29cbc1e3707580165deaff13635ba2fa20450ac8a868ce368f62aac5d59df9b1643048675d51215d90a29992aafab7b18b4bb5a6abdbe41773fe900

test:
  secret_key_base: 4caeea46114db17d7ff506e210e654292ab1d0c5d6c06b9a77624a164ee0a127f6cd661c497cc8e4f8017fe71f92859f04f3e750d6dfddcfb923eab6c8400cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
